version: '3.8'

services:
  m3u-converter:
    build: .
    container_name: m3u-converter
    ports:
      - "8768:8768"
    volumes:
      - /mnt/m3utostrm/data:/app/data
      - /mnt/m3utostrm/logs:/app/logs
      - /mnt/m3utostrm/content:/app/content
      - /mnt/m3utostrm/uploads:/app/uploads
    restart: unless-stopped
    environment:
      - TZ=UTC
